import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import { env } from "./config/env.js";
import authRoutes from "./routes/authRoutes.js";
import bookRoutes from "./routes/bookRoutes.js";
import borrowRoutes from "./routes/borrowRoutes.js";
import myBorrowedRoutes from "./routes/myBorrowedRoutes.js";
import borrowRecordRoutes from "./routes/borrowRecordRoutes.js";
import { errorHandler, notFound } from "./middlewares/errors.js";
export const app = express();
app.use(helmet());
app.use(cors({ origin: env.clientUrl }));
app.use(morgan("dev"));
app.use(express.json());
app.get("/api/health", (_req, res) => res.json({ success: true }));
app.use("/api/auth", authRoutes);
app.use("/api/books", bookRoutes);
app.use("/api/borrow", borrowRoutes);
app.use("/api/my-borrowed-books", myBorrowedRoutes);
app.use("/api/borrow-records", borrowRecordRoutes);
app.use(notFound);
app.use(errorHandler);
